using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurrencyBot.Models
{

    public static class CurrencyList
    {
        private static Dictionary<string, string> CountryCurrency = new Dictionary<string, string>() {
            {"Afghanistan","AFN"},
            {"Albania","ALL"},
            {"Algeria","DZD"},
            {"American Samoa","USD"},
            {"Andorra","EUR"},
            {"Angola","AOA"},
            {"Anguilla","XCD"},
            {"Antarctica","XCD"},
            {"Antigua and Barbuda","XCD"},
            {"Argentina","ARS"},
            {"Armenia","AMD"},
            {"Aruba","AWG"},
            {"Australia","AUD"},
            {"Austria","EUR"},
            {"Azerbaijan","AZN"},
            {"Bahamas","BSD"},
            {"Bahrain","BHD"},
            {"Bangladesh","BDT"},
            {"Barbados","BBD"},
            {"Belarus","BYR"},
            {"Belgium","EUR"},
            {"Belize","BZD"},
            {"Benin","XOF"},
            {"Bermuda","BMD"},
            {"Bhutan","BTN"},
            {"Bolivia","BOB"},
            {"Bosnia-Herzegovina","BAM"},
            {"Botswana","BWP"},
            {"Bouvet Island","NOK"},
            {"Brazil","BRL"},
            {"British Indian Ocean Territory","USD"},
            {"Brunei Darussalam","BND"},
            {"Bulgaria","BGN"},
            {"Burkina Faso","XOF"},
            {"Burundi","BIF"},
            {"Cambodia","KHR"},
            {"Cameroon","XAF"},
            {"Canada","CAD"},
            {"Cape Verde","CVE"},
            {"Cayman Islands","KYD"},
            {"Central African Republic","XAF"},
            {"Chad","XAF"},
            {"Chile","CLP"},
            {"China","CNY"},
            {"Christmas Island","AUD"},
            {"Cocos (Keeling) Islands","AUD"},
            {"Colombia","COP"},
            {"Comoros","KMF"},
            {"Congo","XAF"},
            {"Congo, Dem. Republic","CDF"},
            {"Cook Islands","NZD"},
            {"Costa Rica","CRC"},
            {"Croatia","HRK"},
            {"Cuba","CUP"},
            {"Cyprus","EUR"},
            {"Czech Republic","CZK"},
            {"Denmark","DKK"},
            {"Djibouti","DJF"},
            {"Dominica","XCD"},
            {"Dominican Republic","DOP"},
            {"Ecuador","ECS"},
            {"Egypt","EGP"},
            {"El Salvador","SVC"},
            {"Equatorial Guinea","XAF"},
            {"Eritrea","ERN"},
            {"Estonia","EUR"},
            {"Ethiopia","ETB"},
            {"European Union","EUR"},
            {"Falkland Islands (Malvinas)","FKP"},
            {"Faroe Islands","DKK"},
            {"Fiji","FJD"},
            {"Finland","EUR"},
            {"France","EUR"},
            {"French Guiana","EUR"},
            {"French Southern Territories","EUR"},
            {"Gabon","XAF"},
            {"Gambia","GMD"},
            {"Georgia","GEL"},
            {"Germany","EUR"},
            {"Ghana","GHS"},
            {"Gibraltar","GIP"},
            {"Great Britain","GBP"},
            {"Greece","EUR"},
            {"Greenland","DKK"},
            {"Grenada","XCD"},
            {"Guadeloupe (French)","EUR"},
            {"Guam (USA)","USD"},
            {"Guatemala","QTQ"},
            {"Guernsey","GGP"},
            {"Guinea","GNF"},
            {"Guinea Bissau","GWP"},
            {"Guyana","GYD"},
            {"Haiti","HTG"},
            {"Heard Island and McDonald Islands","AUD"},
            {"Honduras","HNL"},
            {"Hong Kong","HKD"},
            {"Hungary","HUF"},
            {"Iceland","ISK"},
            {"India","INR"},
            {"Indonesia","IDR"},
            {"Iran","IRR"},
            {"Iraq","IQD"},
            {"Ireland","EUR"},
            {"Isle of Man","GBP"},
            {"Israel","ILS"},
            {"Italy","EUR"},
            {"Ivory Coast","XOF"},
            {"Jamaica","JMD"},
            {"Japan","JPY"},
            {"Jersey","GBP"},
            {"Jordan","JOD"},
            {"Kazakhstan","KZT"},
            {"Kenya","KES"},
            {"Kiribati","AUD"},
            {"Korea-North","KPW"},
            {"Korea-South","KRW"},
            {"Kuwait","KWD"},
            {"Kyrgyzstan","KGS"},
            {"Laos","LAK"},
            {"Latvia","LVL"},
            {"Lebanon","LBP"},
            {"Lesotho","LSL"},
            {"Liberia","LRD"},
            {"Libya","LYD"},
            {"Liechtenstein","CHF"},
            {"Lithuania","LTL"},
            {"Luxembourg","EUR"},
            {"Macau","MOP"},
            {"Macedonia","MKD"},
            {"Madagascar","MGF"},
            {"Malawi","MWK"},
            {"Malaysia","MYR"},
            {"Maldives","MVR"},
            {"Mali","XOF"},
            {"Malta","EUR"},
            {"Marshall Islands","USD"},
            {"Martinique (French)","EUR"},
            {"Mauritania","MRO"},
            {"Mauritius","MUR"},
            {"Mayotte","EUR"},
            {"Mexico","MXN"},
            {"Micronesia","USD"},
            {"Moldova","MDL"},
            {"Monaco","EUR"},
            {"Mongolia","MNT"},
            {"Montenegro","EUR"},
            {"Montserrat","XCD"},
            {"Morocco","MAD"},
            {"Mozambique","MZN"},
            {"Myanmar","MMK"},
            {"Namibia","NAD"},
            {"Nauru","AUD"},
            {"Nepal","NPR"},
            {"Netherlands","EUR"},
            {"Netherlands Antilles","ANG"},
            {"New Caledonia (French)","XPF"},
            {"New Zealand","NZD"},
            {"Nicaragua","NIO"},
            {"Niger","XOF"},
            {"Nigeria","NGN"},
            {"Niue","NZD"},
            {"Norfolk Island","AUD"},
            {"Northern Mariana Islands","USD"},
            {"Norway","NOK"},
            {"Oman","OMR"},
            {"Pakistan","PKR"},
            {"Palau","USD"},
            {"Panama","PAB"},
            {"Papua New Guinea","PGK"},
            {"Paraguay","PYG"},
            {"Peru","PEN"},
            {"Philippines","PHP"},
            {"Pitcairn Island","NZD"},
            {"Poland","PLN"},
            {"Polynesia (French)","XPF"},
            {"Portugal","EUR"},
            {"Puerto Rico","USD"},
            {"Qatar","QAR"},
            {"Reunion (French)","EUR"},
            {"Romania","RON"},
            {"Russia","RUB"},
            {"Rwanda","RWF"},
            {"Saint Helena","SHP"},
            {"Saint Kitts & Nevis Anguilla","XCD"},
            {"Saint Lucia","XCD"},
            {"Saint Pierre and Miquelon","EUR"},
            {"Saint Vincent & Grenadines","XCD"},
            {"Samoa","WST"},
            {"San Marino","EUR"},
            {"Sao Tome and Principe","STD"},
            {"Saudi Arabia","SAR"},
            {"Senegal","XOF"},
            {"Serbia","RSD"},
            {"Seychelles","SCR"},
            {"Sierra Leone","SLL"},
            {"Singapore","SGD"},
            {"Slovakia","EUR"},
            {"Slovenia","EUR"},
            {"Solomon Islands","SBD"},
            {"Somalia","SOS"},
            {"South Africa","ZAR"},
            {"South Georgia & South Sandwich Islands","GBP"},
            {"South Sudan","SSP"},
            {"Spain","EUR"},
            {"Sri Lanka","LKR"},
            {"Sudan","SDG"},
            {"Suriname","SRD"},
            {"Svalbard and Jan Mayen Islands","NOK"},
            {"Swaziland","SZL"},
            {"Sweden","SEK"},
            {"Switzerland","CHF"},
            {"Syria","SYP"},
            {"Taiwan","TWD"},
            {"Tajikistan","TJS"},
            {"Tanzania","TZS"},
            {"Thailand","THB"},
            {"Togo","XOF"},
            {"Tokelau","NZD"},
            {"Tonga","TOP"},
            {"Trinidad and Tobago","TTD"},
            {"Tunisia","TND"},
            {"Turkey","TRY"},
            {"Turkmenistan","TMT"},
            {"Turks and Caicos Islands","USD"},
            {"Tuvalu","AUD"},
            {"United Kingdom (UK)","GBP"},
            {"England","GBP"},
            {"United States of America (USA)","USD"},
            {"USA Minor Outlying Islands","USD"},
            {"Uganda","UGX"},
            {"Ukraine","UAH"},
            {"United Arab Emirates","AED"},
            {"Uruguay","UYU"},
            {"Uzbekistan","UZS"},
            {"Vanuatu","VUV"},
            {"Vatican","EUR"},
            {"Venezuela","VEF"},
            {"Vietnam","VND"},
            {"Virgin Islands (British)","USD"},
            {"Virgin Islands (USA)","USD"},
            {"Wallis and Futuna Islands","XPF"},
            {"Western Sahara","MAD"},
            {"Yemen","YER"},
            {"Zambia","ZMW"},
            {"Zimbabwe","ZWD"}
        };

        public static Dictionary<string, string> GetCountryCurrency()
        {
            return CountryCurrency;
        }

        public static bool DoesCurrencyExist(string curr)
        {
            curr = curr.ToUpper();
            var ret = CountryCurrency.ContainsValue(curr);
            return ret;
        }

        public static string[] GetListCountry(string curr)
        {
            curr = curr.ToLower();
            var ret = CountryCurrency.Where(m => m.Key.ToLower().Contains(curr)).Select(t => t.Key);
            return ret.ToArray();

        }

        public static string GetCurrencyFromCountry(string curr)
        {
            curr = curr.ToLower();
            var ret = CountryCurrency.Where(m => m.Key.ToLower().Contains(curr)).Select(t => t.Value);
            return ret.First();


        }
    }
}